version: '3.7'
services:
    postgres:
        image: postgres:15
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5432:5432'
        volumes:
        - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local